import { ApiProperty } from '@nestjs/swagger';
import { IsBoolean, IsEnum, IsNotEmpty, IsOptional, IsString } from 'class-validator';

export enum DosDontsType {
  DO = 'DO',
  DONT = 'DONT',
}

export class CreateDoAndDontDto {
  @ApiProperty({ enum: DosDontsType })
  @IsEnum(DosDontsType)
  @IsNotEmpty()
  type: DosDontsType;

  @ApiProperty({ example: 'Regular exercise at least 30 minutes daily' })
  @IsString()
  @IsNotEmpty()
  description: string;

  @ApiProperty({ example: false, required: false, default: false })
  @IsBoolean()
  @IsOptional()
  isAutoGenerated?: boolean;
}

export class UpdateDoAndDontDto {
  @ApiProperty({ enum: DosDontsType, required: false })
  @IsEnum(DosDontsType)
  @IsOptional()
  type?: DosDontsType;

  @ApiProperty({ example: 'Regular exercise at least 30 minutes daily', required: false })
  @IsString()
  @IsOptional()
  description?: string;

  @ApiProperty({ example: false, required: false })
  @IsBoolean()
  @IsOptional()
  isAutoGenerated?: boolean;
} 